### ISSUE TITLE
EcoData install

### ISSUE THREAD

**Issue by florianhartig** [TheoreticalEcology/AdvancedBiostatistics#12]
Hi Matthias,

weil du hier https://github.com/TheoreticalEcology/AdvancedBiostatistics/issues/4 sagst es funktionier nicht - was genau funktioniert nicht an: 

```
devtools::install_github(repo = "florianhartig/EcoData", subdir = "EcoData",
                         dependencies = TRUE, build_vignettes = TRUE)
```

**Comment by Meier-Matthias** [comment]
![EcoData](https://user-images.githubusercontent.com/86783340/173603443-6cfffe04-520e-4c35-9dc8-0cf523175188.png)

**Comment by florianhartig** [comment]
This is solved, was the wrong path
